import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
console.log('Launching browser');
const browser = await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,timeout:20000,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],defaultViewport:{width:1600,height:900}});
try {
  const page = await browser.newPage();
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL('index.html').href,{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('.cover-art').naturalWidth===2048);
  assert.equal(await page.$eval('#game-cover',e=>e.hidden),false);
  assert.equal(await page.$eval('.cover-name',e=>e.textContent),'PatientDig');
  assert.match(await page.$eval('#cover-start',e=>e.textContent),/Start Game/);
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.evaluate(()=>document.fonts.check('48px "Lilita One"')),true);
  mkdirSync('tests/out',{recursive:true});
  await page.screenshot({path:'tests/out/cover-desktop.png'});
  await page.setViewport({width:390,height:844});
  await page.screenshot({path:'tests/out/cover-mobile.png'});
  await page.click('#cover-start');
  assert.equal(await page.$eval('#game-cover',e=>e.hidden),true);
  assert.equal(await page.$eval('#game-story',e=>e.hidden),false);
  await page.waitForFunction(()=>!document.getElementById('story-next').disabled);
  await page.screenshot({path:'tests/out/story-mobile.png'});
  await page.setViewport({width:1600,height:900});
  for (let i=0;i<4;i++) {
    await page.waitForFunction(()=>!document.getElementById('story-next').disabled);
    assert.equal(await page.$eval('#story-page',e=>e.textContent),`${String(i+1).padStart(2,'0')} / 04`);
    assert.equal(await page.$$eval('.story-image',els=>els.filter(e=>!e.hidden).length),1);
    assert.ok((await page.$eval('.story-image:not([hidden])',e=>e.src)).endsWith(`intro-${i+1}.webp`));
    await page.click('.story-frame');
    await new Promise(r=>setTimeout(r,600));
    assert.equal(await page.$eval('#story-page',e=>e.textContent),`${String(i+1).padStart(2,'0')} / 04`);
    await page.screenshot({path:`tests/out/story-${i+1}.png`});
    await page.click('#story-next');
  }
  assert.equal(await page.$eval('#game-story',e=>e.hidden),true);
  await page.waitForFunction(()=>window.__home?.ready,{timeout:60000});
  assert.equal(await page.evaluate(()=>__home.loaded.length),7);
  await page.screenshot({path:'tests/out/home-map.png'});
  await page.click('[data-pin="liaoning"]');
  assert.equal(await page.$eval('#depart',e=>e.disabled),true);
  await page.click('[data-pin="heyuan"]');
  assert.equal(await page.evaluate(()=>__home.selected),'heyuan');
  await page.click('[data-pin="sichuan"]');
  assert.equal(await page.$eval('#depart',e=>e.disabled),false);
  await page.click('#nav-catalog');
  assert.equal(await page.evaluate(()=>__home.mode),'catalog');
  await page.click('[data-specimen="feather"]');
  await page.screenshot({path:'tests/out/home-specimen.png'});
  await page.click('#nav-map');
  await page.setViewport({width:390,height:844});
  await page.screenshot({path:'tests/out/home-mobile.png'});
  await page.click('#nav-catalog');
  await page.screenshot({path:'tests/out/catalog-mobile.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  await page.setViewport({width:1600,height:900});
  await page.click('#nav-map');
  assert.equal(await page.$eval('#language-toggle',e=>getComputedStyle(e).pointerEvents),'auto');
  assert.equal(await page.$eval('#language-toggle',e=>getComputedStyle(e).cursor),'pointer');
  await page.click('#language-toggle');
  await page.waitForFunction(()=>document.documentElement.lang==='en');
  assert.equal(await page.$eval('html',e=>e.lang),'en');
  assert.equal(await page.$eval('#language-toggle > span:first-child',e=>e.textContent),'A');
  assert.equal(await page.$eval('#language-toggle .language-label',e=>e.textContent),'中文');
  assert.equal(await page.$eval('#chapter h2',e=>e.textContent),'Where to next?');
  assert.equal(await page.$eval('#report-title',e=>e.textContent),'The “dragon bones” of Shitouchong');
  assert.equal(await page.$eval('#nav-map .nav-text',e=>e.textContent),'Map');
  assert.equal(await page.$eval('#depart',e=>e.textContent),'Investigate →');
  await page.click('#nav-catalog');
  assert.equal(await page.$eval('#catalog-info .kicker',e=>e.textContent),'FIELD COLLECTION / STUDY TABLE');
  await page.click('[data-specimen="heping"]');
  assert.equal(await page.$eval('#specimen-title',e=>e.textContent),'Yangchuanosaurus');
  await page.click('#language-toggle');
  await page.waitForFunction(()=>document.documentElement.lang==='zh-CN');
  assert.equal(await page.$eval('html',e=>e.lang),'zh-CN');
  assert.equal(await page.$eval('#language-toggle > span:first-child',e=>e.textContent),'文');
  assert.equal(await page.$eval('#language-toggle .language-label',e=>e.textContent),'English');
  assert.equal(await page.$eval('#nav-catalog .nav-text',e=>e.textContent),'野外图鉴');
  assert.equal(await page.$eval('#specimen-title',e=>e.textContent),'和平永川龙');
  await page.click('#sound');
  assert.equal(await page.evaluate(()=>window.__patientDigMusic.enabled),false);
  assert.match(await page.$eval('#sound',e=>e.textContent),/声音：关|Sound: Off/);
  await page.click('#sound');
  assert.equal(await page.evaluate(()=>window.__patientDigMusic.enabled),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: cover, four ordered illustrations, arrow-only progression, desktop/mobile, map entry, 7 models, catalog, no errors');
} finally { await browser.close(); }
