import puppeteer from 'puppeteer-core';
import { existsSync, mkdirSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const executablePath=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p=>p&&existsSync(p));
const browser=await puppeteer.launch({executablePath,headless:true,pipe:true,timeout:30000,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],defaultViewport:{width:1440,height:960}});
const page=await browser.newPage();const errors=[];
page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message);});
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
mkdirSync('tests/out',{recursive:true});
try {
 await page.evaluateOnNewDocument(()=>{window.__TEST__=true;});
 await page.goto(pathToFileURL('index.html').href,{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForFunction(()=>window.__home?.ready,{timeout:60000});
 assert.equal((await page.evaluate(()=>__home.loaded)).length,7);
 await wait(600);await page.screenshot({path:'tests/out/home-map.png'});
 console.log('READY',await page.evaluate(()=>__home.stats()));
 await page.click('[data-pin="liaoning"]');
 assert.equal(await page.$eval('#report-location',e=>e.textContent),'辽宁 · 北票 · 热河生物群');
 assert.equal(await page.$eval('#depart',e=>e.disabled),true);
 await page.click('[data-pin="heyuan"]');assert.equal(await page.evaluate(()=>__home.selected),'heyuan');
 await page.click('[data-pin="sichuan"]');assert.equal(await page.$eval('#depart',e=>e.disabled),false);
 await page.click('#nav-catalog');assert.equal(await page.evaluate(()=>__home.mode),'catalog');
 await page.click('[data-specimen="feather"]');assert.equal(await page.evaluate(()=>__home.specimen),'feather');
 await wait(400);await page.screenshot({path:'tests/out/home-specimen.png'});
 await page.click('[data-specimen="rock"]');assert.equal(await page.evaluate(()=>__home.specimen),'rock');
 await page.click('#nav-map');
 const radio=await page.evaluate(()=>__home.screenPoint('radio'));console.log('radio',radio);
 await page.mouse.click(radio.x,radio.y);assert.ok(await page.$eval('#toast',e=>e.textContent.length>0));
 const start=await page.$eval('[data-pin="sichuan"]',e=>e.getBoundingClientRect().x);
 await page.mouse.move(720,340);await page.mouse.down();await page.mouse.move(870,370,{steps:15});await page.mouse.up();await wait(500);
 const end=await page.$eval('[data-pin="sichuan"]',e=>e.getBoundingClientRect().x);assert.ok(Math.abs(start-end)>2,'camera orbit moves map labels');
 await page.click('#reset-view');
 await page.setViewport({width:390,height:844});await wait(600);await page.screenshot({path:'tests/out/home-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.setViewport({width:1440,height:960});await page.click('#nav-catalog');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__home?.ready,{timeout:60000});assert.equal(await page.evaluate(()=>__home.mode),'catalog');
 await page.evaluate(()=>localStorage.setItem('datday.catalog',JSON.stringify(['heping'])));await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__home?.ready,{timeout:60000});assert.equal(await page.evaluate(()=>__home.earned),true);assert.equal(await page.$eval('#catalog-count',e=>e.textContent),'01');
 await page.click('#nav-map');await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.click('#depart')]);assert.ok(page.url().endsWith('/3d.html'));
 assert.deepEqual(errors,[]);console.log('PASS: local-file loading, 7 assets, locations, locked routes, specimen catalog, 3D object picking, orbit, mobile, saved catalog and departure');
} finally {await browser.close();}
